### ISSUE TITLE
changing the file in mdb.yaml does not point to a new file

### ISSUE THREAD

**Issue by Abraxas3d** [yamcs/xtce-extractor#1]
"The XTCE database is configured in src/main/resources/mdb.yaml. Currently it points to an XML file in the mdb directory"

Changing the name of the file in mdb.yaml does not seem to point to a new file. 

Putting in a bogus name still results in success when running the jar file.

**Comment by fqqb** [comment]
Hi, mdb.yaml is packaged inside the jar in this project. So you would need to ``mvn clean package`` again after making any changes.

Sidenote: this example project is a bit outdated. I'll prepare an update somewhere next week to use latest Yamcs, and change a bit the structure.

**Comment by fqqb** [comment]
This repo is getting archived. The code example has been transferred to our main repo: https://github.com/yamcs/yamcs/blob/master/examples/snippets/src/main/java/org/yamcs/examples/snippets/XtceDecodingSnippet.java
